env: local

deps:
  config:
    path: app.Config
    module: load
    args:
      - config/app-local.yml

  logger:
    path: log.driver.FileLogger
    module: FileLogger
    args:
      - DEBUG
      - logs/app.log

  app:
    path: app.App
    module: App
    args:
      - $deps.config
      - $deps.logger

